#pragma once

#include <FrenchieApplicationImmediate2DRenderer.hpp>

// STL
#include <type_traits>
#include <memory>
#include <chrono>
#include <stack>
#include <map>
#include <set>

namespace Frenchie
{
    namespace Application
    {
        enum ImmediateUserInterfaceMouseHover_ : int
        {
            ImmediateUserInterfaceMouseHover_None         = 0,
            ImmediateUserInterfaceMouseHover_MouseLeft    = 1 << 0,
            ImmediateUserInterfaceMouseHover_MouseHovered = 1 << 1,
            ImmediateUserInterfaceMouseHover_MouseEntered = 1 << 2,
        };

        enum ImmediateUserInterfaceNodeSettings_ : int
        {
            ImmediateUserInterfaceNodeSettings_None                         = 0,
            ImmediateUserInterfaceNodeSettings_Movable                      = 1 << 0,
            ImmediateUserInterfaceNodeSettings_Resizable                    = 1 << 1,
            ImmediateUserInterfaceNodeSettings_LayoutChildrenVertically     = 1 << 2,
            ImmediateUserInterfaceNodeSettings_LayoutChildrenHorizontally   = 1 << 3,
            ImmediateUserInterfaceNodeSettings_LayoutChildrenWithNativeSize = 1 << 4
        };

        enum ImmediateUserInterfaceNodeEvents_ : int
        {
            ImmediateUserInterfaceNodeEvents_None                 = 0,
            ImmediateUserInterfaceNodeEvents_IsMoved              = 1 << 0,
            ImmediateUserInterfaceNodeEvents_IsResizedTop         = 1 << 1,
            ImmediateUserInterfaceNodeEvents_IsResizedLeft        = 1 << 2,
            ImmediateUserInterfaceNodeEvents_IsResizedRight       = 1 << 3,
            ImmediateUserInterfaceNodeEvents_IsResizedBottom      = 1 << 4,
            ImmediateUserInterfaceNodeEvents_IsResizedTopLeft     = 1 << 5,
            ImmediateUserInterfaceNodeEvents_IsResizedTopRight    = 1 << 6,
            ImmediateUserInterfaceNodeEvents_IsResizedBottomLeft  = 1 << 7,
            ImmediateUserInterfaceNodeEvents_IsResizedBottomRight = 1 << 8,
        };

        typedef int ImmediateUserInterfaceNodeMouseHover;
        typedef int ImmediateUserInterfaceNodeSettings;
        typedef int ImmediateUserInterfaceNodeEvents;

        class ImmedidateUserInterfaceContextLayer;
        struct ImmedidateUserInterfaceNode;
        struct ImmedidateUserInterfaceEvent;

        struct ImmedidateUserInterfaceEvent
        {
            gs_vec2f             CursorPosition {gs_vec2f(0.f, 0.f)};
            gs_vec2f             CursorDragDelta{gs_vec2f(0.f, 0.f)};

            Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseDown;
            Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseHold;
            Frenchie::Core::Optional<ApplicationMouseButton::Button> MousePressed;
            Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseClicked;
            Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseDoubleClicked;
        };
        
        struct ImmedidateUserInterfaceNode
        {
            ImmedidateUserInterfaceNode(const std::string _Name);
            virtual ~ImmedidateUserInterfaceNode();

            virtual void render(ImmedidateUserInterfaceContextLayer*);
            virtual void layout(ImmedidateUserInterfaceContextLayer*);
            // virtual bool hover (Immediate2DRenderer* _Renderer, const UIEvent& _Event);
            // virtual bool input (Immediate2DRenderer* _Renderer, const UIEvent& _Event);
            // virtual bool event (Immediate2DRenderer* _Renderer, const UIEvent& _Event);

            bool is_visible() const;
            bool is_partially_visible() const;

            int place_in_follow()
            {
                State.TotalThickness += (++State.SelfThickness);
                return State.Depth + State.SelfThickness;
            }

            struct Data
            {
                // rendering
                int            Depth         {0};
                int            SelfThickness {0}; // thickness of the content generated by render(...) function
                int            TotalThickness{0}; // thickness of the content generated by render(...) function and children
                int            RenderingIndex{0};

                // geimetry
                gs_2dboxf      BoundingBox{gs_2dboxf(gs_vec2f(32.f, 32.f), gs_vec2f(1024.f, 512.f))};
                gs_vec2f       MinimumSize{gs_vec2f(4.f)};
                gs_vec2f       MaximumSize{gs_vec2f((float)INT_MAX)};

                // hierarchy
                ImmedidateUserInterfaceNode*        Parent{nullptr};

                // settings
                ImmediateUserInterfaceNodeSettings Settings{ImmediateUserInterfaceNodeSettings_::ImmediateUserInterfaceNodeSettings_LayoutChildrenVertically};

                // events
                ImmediateUserInterfaceNodeEvents   Events{ImmediateUserInterfaceNodeEvents_::ImmediateUserInterfaceNodeEvents_None};

                // mouse hover
                ImmediateUserInterfaceNodeMouseHover           MouseHover{ImmediateUserInterfaceMouseHover_::ImmediateUserInterfaceMouseHover_None};
                std::chrono::high_resolution_clock::time_point MouseEnterTimer;
                std::chrono::high_resolution_clock::time_point MouseLeaveTimer;

                // mouse and keyboard input
                // TODO: implement keyboard input !!!
                Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseDown;
                Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseHold;
                Frenchie::Core::Optional<ApplicationMouseButton::Button> MousePressed;
                Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseClicked;
                Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseDoubleClicked;
            };

            Data State;
            Data Cache;

        //private:
            std::string Name = "UINode";
        };

        class ImmedidateUserInterfaceContextLayer : public Layer
        {
        public:
            ImmedidateUserInterfaceContextLayer();
            virtual ~ImmedidateUserInterfaceContextLayer();

            virtual bool awake()        override;
            virtual void frame_start()  override;
            virtual void frame_update() override;
            virtual void frame_debug()  override;
            virtual void frame_render() override;
            virtual void frame_finish() override;

            bool begin_node(const std::string& _Name, const ImmediateUserInterfaceNodeSettings& _Settings)
            {
                // create node
                if(m_Cache.find(_Name) == m_Cache.end())
                    m_Cache[_Name] = std::make_unique<ImmedidateUserInterfaceNode>(_Name);
                ImmedidateUserInterfaceNode* node = m_Cache[_Name].get();

                node->State.Settings  = _Settings;
                node->State.RenderingIndex = m_NodesRenderingList.size();

                // build nodes hierarchy
                if(!m_NodesRenderingStack.empty())
                    node->State.Parent = m_NodesRenderingStack[m_NodesRenderingStack.size() - 1];

                m_NodesRenderingList.push_back(node);
                m_NodesRenderingStack.push_back(node);

                return true;
            }

            void end_node()
            {
                if(!m_NodesRenderingStack.empty())
                    m_NodesRenderingStack.pop_back();
            }

        //private:

            struct Hierarchy
            {
                Hierarchy(const std::function<ImmedidateUserInterfaceNode*(ImmedidateUserInterfaceNode*)> _GetParent =
                    [](ImmedidateUserInterfaceNode* _Node)->ImmedidateUserInterfaceNode*
                    {
                        return _Node != nullptr ? _Node->State.Parent : nullptr;
                    }) : GetParent(_GetParent){}

                ~Hierarchy(){}

                std::vector<int>                                     Indexes;
                std::vector<int>                                     Entries;
                std::vector<ImmedidateUserInterfaceNode*>            Singletons;
                std::vector<ImmedidateUserInterfaceNode*>            Sorted;
                std::function<ImmedidateUserInterfaceNode*(ImmedidateUserInterfaceNode*)> GetParent;

                std::vector<ImmedidateUserInterfaceNode*>::const_iterator begin(const ImmedidateUserInterfaceNode* _Node) const
                {
                    return Sorted.empty() ? Sorted.end() : Sorted.begin() + Indexes[_Node->State.RenderingIndex];
                }

                std::vector<ImmedidateUserInterfaceNode*>::const_iterator end(const ImmedidateUserInterfaceNode* _Node) const
                {
                    return Sorted.empty() ? Sorted.end() : Sorted.begin() + Indexes[_Node->State.RenderingIndex + 1];
                }

                void build(const std::vector<ImmedidateUserInterfaceNode*>& _Nodes)
                {
                    std::vector<int> workspace(_Nodes.size()+1);

                    Indexes.resize(_Nodes.size() + 1);
                    Entries.resize(_Nodes.size());
                    Sorted.resize(_Nodes.size());
                    Singletons.clear();

                    for(int i = 0; i < (int)Entries.size(); i++)
                    {
                        Entries[i] = 0;
                        Indexes[i] = 0;
                        Sorted [i] = nullptr;

                        if(_Nodes[i]->State.Parent == nullptr)
                            Singletons.push_back(_Nodes[i]);
                    }

                    // count items
                    for (int i = 0; i < (int)_Nodes.size(); i++)
                    {
                        if(get_parent(_Nodes[i]) == nullptr)
                            continue;

                        ++Entries[get_parent(_Nodes[i])->State.RenderingIndex];
                    }

                    // cumulative sum
                    int sum = 0;
                    for (int i = 0; i < _Nodes.size(); i++)
                    {
                        Indexes  [i] = sum;
                        workspace[i] = sum;
                        sum += Entries[i];
                    }
                    Indexes[_Nodes.size()] = sum;

                    for(int i = 0; i < _Nodes.size(); i++ )
                    {
                        if(get_parent(_Nodes[i]) == nullptr)
                            continue;

                        Sorted[workspace[get_parent(_Nodes[i])->State.RenderingIndex]++] = _Nodes[i];
                    }
                }

            private:

                ImmedidateUserInterfaceNode* get_parent(ImmedidateUserInterfaceNode* _Node)
                {
                    return GetParent != nullptr ? GetParent(_Node) : nullptr;
                }
            };

            mutable std::map<std::string, std::unique_ptr<ImmedidateUserInterfaceNode>> m_Cache;
            mutable Hierarchy                                      m_Hierarchy;
            mutable std::shared_ptr<Immediate2DRenderer>           m_Renderer           {nullptr};
            mutable std::vector<ImmedidateUserInterfaceNode*>                           m_NodesRenderingList {std::vector<ImmedidateUserInterfaceNode*>()};
            mutable std::vector<ImmedidateUserInterfaceNode*>                           m_NodesRenderingCache{std::vector<ImmedidateUserInterfaceNode*>()};
            mutable std::vector<ImmedidateUserInterfaceNode*>                           m_NodesRenderingStack{std::vector<ImmedidateUserInterfaceNode*>()};
        };
    };
}