#pragma once

#include <FrenchieApplicationImmediate2DRenderer.hpp>

// STL
#include <type_traits>
#include <memory>
#include <chrono>
#include <stack>
#include <map>
#include <set>

namespace Frenchie
{
    namespace Application
    {
        enum UINodeMouseHover_ : int
        {
            UINodeMouseHover_None         = 0,
            UINodeMouseHover_MouseLeft    = 1 << 0,
            UINodeMouseHover_MouseHovered = 1 << 1,
            UINodeMouseHover_MouseEntered = 1 << 2,
        };

        enum UINodeSettings_ : int
        {
            // sentinel
            UINodeSettings_None                         = 0,
            UINodeSettings_Movable                      = 1 << 0,
            UINodeSettings_Resizable                    = 1 << 1,
            UINodeSettings_LayoutChildrenVertically     = 1 << 2,
            UINodeSettings_LayoutChildrenHorizontally   = 1 << 3,
            UINodeSettings_LayoutChildrenWithNativeSize = 1 << 4
        };

        enum UINodeEvents_ : int
        {
            UINodeEvents_None                    = 0,
            UINodeEvents_IsMoved                 = 1 << 0,
            UINodeEvents_IsResizedTop            = 1 << 1,
            UINodeEvents_IsResizedLeft           = 1 << 2,
            UINodeEvents_IsResizedRight          = 1 << 3,
            UINodeEvents_IsResizedBottom         = 1 << 4,
            UINodeEvents_IsResizedTopLeft        = 1 << 5,
            UINodeEvents_IsResizedTopRight       = 1 << 6,
            UINodeEvents_IsResizedTopBottomLeft  = 1 << 7,
            UINodeEvents_IsResizedTopBottomRight = 1 << 8,
        };

        typedef int UINodeMouseHover;
        typedef int UINodeSettings;
        typedef int UINodeEvents;

        struct UINode;
        struct UIEvent;

        struct UIEvent
        {
            gs_vec2f             CursorPosition {gs_vec2f(0.f, 0.f)};
            gs_vec2f             CursorDragDelta{gs_vec2f(0.f, 0.f)};

            Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseDown;
            Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseHold;
            Frenchie::Core::Optional<ApplicationMouseButton::Button> MousePressed;
            Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseClicked;
            Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseDoubleClicked;
        };
        
        struct UINode
        {
            UINode(const std::string _Name);
            virtual ~UINode();

            virtual void render(Immediate2DRenderer* _Renderer);
            // virtual bool hover (Immediate2DRenderer* _Renderer, const UIEvent& _Event);
            // virtual bool input (Immediate2DRenderer* _Renderer, const UIEvent& _Event);
            // virtual bool event (Immediate2DRenderer* _Renderer, const UIEvent& _Event);

            bool is_visible() const;
            bool is_partially_visible() const;

            int place_in_follow()
            {
                State.TotalThickness += (++State.SelfThickness);
                return State.Depth + State.SelfThickness;
            }

            struct Data
            {
                // rendering
                int            Depth         {0};
                int            SelfThickness {0}; // thickness of the content generated by render(...) function
                int            TotalThickness{0}; // thickness of the content generated by render(...) function and children
                int            RenderingIndex{0};

                // geimetry
                gs_2dboxf      BoundingBox{gs_2dboxf(gs_vec2f(0.f, 0.f), gs_vec2f(1024.f, 512.f))};
                gs_vec2f       MinimumSize{gs_vec2f(4.f)};
                gs_vec2f       MaximumSize{gs_vec2f((float)INT_MAX)};

                // hierarchy
                UINode*        Parent{nullptr};

                // settings
                UINodeSettings Settings{UINodeSettings_::UINodeSettings_LayoutChildrenVertically};

                // events
                UINodeEvents   Events{UINodeEvents_::UINodeEvents_None};

                // mouse hover
                UINodeMouseHover                               MouseHover{UINodeMouseHover_::UINodeMouseHover_None};
                std::chrono::high_resolution_clock::time_point MouseEnterTimer;
                std::chrono::high_resolution_clock::time_point MouseLeaveTimer;

                // mouse and keyboard input
                // TODO: implement keyboard input !!!
                Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseDown;
                Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseHold;
                Frenchie::Core::Optional<ApplicationMouseButton::Button> MousePressed;
                Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseClicked;
                Frenchie::Core::Optional<ApplicationMouseButton::Button> MouseDoubleClicked;
            };

            Data State;
            Data Cache;

        //private:
            std::string Name = "UINode";
        };

        class ImmedidateUserInterfaceContextLayer2 : public Layer
        {
        public:
            ImmedidateUserInterfaceContextLayer2();
            virtual ~ImmedidateUserInterfaceContextLayer2();

            virtual bool awake()        override;
            virtual void frame_start()  override;
            virtual void frame_update() override;
            virtual void frame_debug()  override;
            virtual void frame_render() override;
            virtual void frame_finish() override;

            bool begin_node(const std::string& _Name, const UINodeSettings& _Settings)
            {
                // create node
                if(m_Cache.find(_Name) == m_Cache.end())
                    m_Cache[_Name] = std::make_unique<UINode>(_Name);
                UINode* node = m_Cache[_Name].get();

                node->State.Settings  = _Settings;
                node->State.RenderingIndex = m_NodesRenderingList.size();

                // build nodes hierarchy
                if(!m_NodesRenderingStack.empty())
                    node->State.Parent = m_NodesRenderingStack[m_NodesRenderingStack.size() - 1];

                m_NodesRenderingList.push_back(node);
                m_NodesRenderingStack.push_back(node);

                return true;
            }

            void end_node()
            {
                if(!m_NodesRenderingStack.empty())
                    m_NodesRenderingStack.pop_back();
            }

        private:

            struct Hierarchy
            {
                Hierarchy(const std::function<UINode*(UINode*)> _GetParent =
                    [](UINode* _Node)->UINode*
                    {
                        return _Node != nullptr ? _Node->State.Parent : nullptr;
                    }) : GetParent(_GetParent){}

                ~Hierarchy(){}

                std::vector<int>                Indexes;
                std::vector<int>                Entries;
                std::vector<UINode*>            Singletons;
                std::vector<UINode*>            Sorted;
                std::function<UINode*(UINode*)> GetParent;

                std::vector<UINode*>::const_iterator begin(const UINode* _Node) const
                {
                    return Sorted.empty() ? Sorted.end() : Sorted.begin() + Indexes[_Node->State.RenderingIndex];
                }

                std::vector<UINode*>::const_iterator end(const UINode* _Node) const
                {
                    return Sorted.empty() ? Sorted.end() : Sorted.begin() + Indexes[_Node->State.RenderingIndex + 1];
                }

                void build(const std::vector<UINode*>& _Nodes)
                {
                    std::vector<int> workspace(_Nodes.size()+1);

                    Indexes.resize(_Nodes.size() + 1);
                    Entries.resize(_Nodes.size());
                    Sorted.resize(_Nodes.size());
                    Singletons.clear();

                    for(int i = 0; i < (int)Entries.size(); i++)
                    {
                        Entries[i] = 0;
                        Indexes[i] = 0;
                        Sorted [i] = nullptr;

                        if(_Nodes[i]->State.Parent == nullptr)
                            Singletons.push_back(_Nodes[i]);
                    }

                    // count items
                    for (int i = 0; i < (int)_Nodes.size(); i++)
                    {
                        if(get_parent(_Nodes[i]) == nullptr)
                            continue;

                        ++Entries[get_parent(_Nodes[i])->State.RenderingIndex];
                    }

                    // cumulative sum
                    int sum = 0;
                    for (int i = 0; i < _Nodes.size(); i++)
                    {
                        Indexes  [i] = sum;
                        workspace[i] = sum;
                        sum += Entries[i];
                    }
                    Indexes[_Nodes.size()] = sum;

                    for(int i = 0; i < _Nodes.size(); i++ )
                    {
                        if(get_parent(_Nodes[i]) == nullptr)
                            continue;

                        Sorted[workspace[get_parent(_Nodes[i])->State.RenderingIndex]++] = _Nodes[i];
                    }
                }

            private:

                UINode* get_parent(UINode* _Node)
                {
                    return GetParent != nullptr ? GetParent(_Node) : nullptr;
                }
            };

            mutable std::map<std::string, std::unique_ptr<UINode>> m_Cache;
            mutable Hierarchy                                      m_Hierarchy;
            mutable std::shared_ptr<Immediate2DRenderer>           m_Renderer           {nullptr};
            mutable std::vector<UINode*>                           m_NodesRenderingList {std::vector<UINode*>()};
            mutable std::vector<UINode*>                           m_NodesRenderingCache{std::vector<UINode*>()};
            mutable std::vector<UINode*>                           m_NodesRenderingStack{std::vector<UINode*>()};
        };
    };
}