include(FetchContent)

# load SDL from remote
FetchContent_Declare(
    GLFW
    GIT_REPOSITORY ${FRENCHIE_PLATFORM_BACKEND_GLFW_GIT_REPO_LINK}
    GIT_TAG ${FRENCHIE_PLATFORM_BACKEND_GLFW_GIT_REPO_BRANCH}
    OVERRIDE_FIND_PACKAGE)

# configure GLFW
set(GLFW_BUILD_DOCS OFF CACHE BOOL "Build GLFW docs" FORCE)
set(GLFW_BUILD_TESTS OFF CACHE BOOL "Build GLFW tests" FORCE)
set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "Build GLFW examples" FORCE)
set(GLFW_LIBRARY_TYPE "STATIC" CACHE STRING "Library type override for GLFW (SHARED, STATIC, OBJECT, or empty to follow BUILD_SHARED_LIBS)" FORCE)

FetchContent_MakeAvailable(GLFW)