include(FetchContent)

# load SDL from remote
FetchContent_Declare(
    SDL3
    GIT_REPOSITORY ${FRENCHIE_PLATFORM_BACKEND_SDL3_GIT_REPO_LINK}
    GIT_TAG ${FRENCHIE_PLATFORM_BACKEND_SDL3_GIT_REPO_BRANCH}
    OVERRIDE_FIND_PACKAGE)

# configure SDL
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_DISABLE_INSTALL ON CACHE BOOL "" FORCE)

FetchContent_MakeAvailable(SDL3)