set(FMT_DOC OFF CACHE BOOL "Build FMT docs" FORCE)
set(FMT_INSTALL OFF CACHE BOOL "Install FMT" FORCE)
set(FMT_TEST OFF CACHE BOOL "Build FMT tests" FORCE)
set(FMT_FUZZ OFF CACHE BOOL "Build FMT fuzz" FORCE)
set(FMT_CUDA_TEST OFF CACHE BOOL "Build FMT/CUDA tests" FORCE)
set(FMT_UNICODE ON CACHE BOOL "Enable FMT UNICODE support" FORCE)
set(FMT_PEDANTIC OFF CACHE BOOL "Enable FMT slow pedantic check" FORCE)
set(FMT_WERROR OFF CACHE BOOL "Enable FMT to throw errors on warnings" FORCE)
set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "Build FMT examples" FORCE)
add_subdirectory("tools/fmt/")