set(FMT_DOC OFF)
set(FMT_INSTALL OFF)
set(FMT_TEST OFF)
set(FMT_FUZZ OFF)
set(FMT_CUDA_TEST OFF)
set(FMT_UNICODE ON)
set(FMT_PEDANTIC OFF)
set(FMT_WERROR OFF)
add_compile_definitions(GLM_ENABLE_EXPERIMENTAL)
add_subdirectory("tools/fmt/")